services:
    rmcgirr83.stopforumspam.admin.controller:
        class: rmcgirr83\stopforumspam\controller\admin_controller
        arguments:
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@rmcgirr83.stopforumspam.core.sfsgroups'
            - '%core.root_path%'
            - '%core.php_ext%'

    rmcgirr83.stopforumspam.mainlistener:
        class: rmcgirr83\stopforumspam\event\main_listener
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@rmcgirr83.stopforumspam.core.sfsgroups'
            - '@rmcgirr83.stopforumspam.core.sfsapi'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@?rmcgirr83.contactadmin.main.controller'
        tags:
            - { name: event.listener }

    rmcgirr83.stopforumspam.core.reporttosfs:
        class: rmcgirr83\stopforumspam\core\reporttosfs
        arguments:
            - '@auth'
            - '@config'
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@user'
            - '@rmcgirr83.stopforumspam.core.sfsgroups'
            - '@rmcgirr83.stopforumspam.core.sfsapi'

    rmcgirr83.stopforumspam.core.report_pm_to_sfs:
        class: rmcgirr83\stopforumspam\core\report_pm_to_sfs
        arguments:
            - '@config'
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@user'
            - '@rmcgirr83.stopforumspam.core.sfsgroups'
            - '@rmcgirr83.stopforumspam.core.sfsapi'

    rmcgirr83.stopforumspam.core.sfsgroups:
        class: rmcgirr83\stopforumspam\core\sfsgroups
        arguments:
            - '@auth'
            - '@cache'

    rmcgirr83.stopforumspam.core.sfsapi:
        class: rmcgirr83\stopforumspam\core\sfsapi
        arguments:
            - '@config'
            - '@language'
            - '@log'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
